name: Test

on:
  push:
    branches:
      - '**'

jobs:
  backend-tests:
    name: Run rspec

    runs-on: ubuntu-20.04

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop
